- name: Reverse Proxy
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:

    - name: Start Reverse proxy
      docker_container:
        name: Nginx_reverse_proxy
        image: jwilder/nginx-proxy:alpine
        pull: true
        ports:
          - "80:80"
        state: started